# Константы пользователя.

MAX_EMAIL_LENGTH = 254
MAX_USERNAME_LENGTH = 150
MAX_FIRST_NAME_LENGTH = 150
MAX_LAST_NAME_LENGTH = 150
USERNAME_REGEX = r'^[\w.@+-]+\Z'
MIN_PASSWORD_LENGTH = 6

# Константы Тега.
MAX_TAG_NAME_LENGTH = 32
MAX_TAG_SLUG_LENGTH = 32

# Константы Ингридиента.
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_INGREDIENT_MEASUREMENT_UNIT_LENGTH = 64
MIN_INGREDIENT_AMOUNT = 1

# Константы Рецепта.
MAX_RECIPE_LINK_LENGTH = 256
MAX_RECIPE_NAME_LENGTH = 256
MAX_COCKING_TIME = 1440
MIN_COCKING_TIME = 1

# Общие константы
MAX_VIEW_LENGTH = 30
# URL = 'http://soulscavengerkitty.ddns.net/s/'
URL = 'http://127.0.0.1:8000/s/'
SHORT_LINK_MAX_POSTFIX = 10
DEFAULT_PAGINATION = 6
