version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: soulscavenger/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: soulscavenger/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    image: soulscavenger/foodgram_gateway
    ports:
      - "9000:80"
    volumes:
      - frontend/build:/usr/share/nginx/html/
      - docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/app/media/
      - data:/app/data/
    depends_on:
      - backend