# Generated by Django 3.2.3 on 2025-02-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': 'recipe_ingredients', 'ordering': ('recipe',), 'verbose_name': 'Связь Рецепт/Ингридиент', 'verbose_name_plural': 'Связи Рецепты/Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'default_related_name': 'recipe_tags', 'ordering': ('recipe',), 'verbose_name': 'Связь Рецепт/Тег', 'verbose_name_plural': 'Связи Рецепты/Теги'},
        ),
    ]
